apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: dev
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: phpapp
        image: 667838161883.dkr.ecr.ap-south-1.amazonaws.com/hello-world-1:hello-world-19
        ports:
            - containerPort: 80
        resources:
          limits:
            memory: "100Mi"
            cpu: "200m"
